# this gets `eval`-ed and must return a string to be included in the
# index html page at the bottom.

# The following variables are documented:
# $_{-version}		SVN release of the running script
# $_{-depth}		subdir depth relative to the "top" with .gallery2
# $_{-title}		title of the current subdir (.title contents)
# $_{-path}		path from the dir that contains .gallery2

"<div class=\"genby\">generated by $_{-version}</div>"
